### PR TITLE
TOOLS-2461 upgrade Manta/Triton 19.[12] components to 19.4

### PR DESCRIPTION
**Pull request by timfoster**

### CODE REVIEW

**Review by trentm — COMMENTED** [review]
This need to wait for kbmapi and mako usage to move to 19.4.0 first (the other PRs on this ticket), right?

**Comment by timfoster** [comment]
Yep, that's right.

**Comment by timfoster** [comment]
At this point, we have no more components using 19.1 or 19.2. I think it's time to remove support to produce origin images for those pkgsrc versions.

**Comment by trentm** [comment]
Those origin image versiosn look unused to me now:

```
Origin Image Bitrot 20200513

  16  old  fd2cc906-8938-11e3-beab-4359c665ac99 sdc-smartos@1.6.3
   0  old  de411e86-548d-11e4-a4b7-3bb60478632a sdc-base@14.2.0
   3  old  18b094b0-eb01-11e5-80c1-175dac7ddf02 sdc-minimal-multiarch-lts@15.4.1
  24  old  04a48d7d-6bb5-4e83-8c3b-e60a99e0f48f triton-origin-multiarch-15.4.1
   0  old  b6ea7cb4-6b90-48c0-99e7-1d34c2895248 triton-origin-multiarch-18.1.0
  --  ---  ------
  22  cur  a9368831-958e-432d-a031-f8ce6768d190 triton-origin-x86_64-18.4.0
   0  cur  cbf116a0-43a5-447c-ad8c-8fa57787351c triton-origin-x86_64-19.1.0
   0  cur  a0d5f456-ba0f-4b13-bfdc-5e9323837ca7 triton-origin-x86_64-19.2.0
   7  cur  59ba2e5e-976f-4e09-8aac-a4a7ef0395f5 triton-origin-x86_64-19.4.0
  --  -----------
  72  total
```

**Review by trentm — APPROVED** [review]

**Pull request merged**
